### ISSUE TITLE
Please support icons in v2.0.0.

### ISSUE THREAD

**Issue by sgbai78** [phosphor-icons/flutter#15]
I tried to use the plus-square icon in flutter, but it was not available.

In phosphoricons.com, there is an example saying that it can be used as below, but it seems that it is not actually updated.

Icon(
   PhosphorIcons. plusSquareThin,
   size: 32.0;
)

**Comment by rektdeckard** [comment]
You can always view what versions each icon is available in in the panel. This icon is only available in 2.0.0+, and since 2.0.0 isn't released yet for flutter, it's not available. 

That said, the update will go live tomorrow.

**Comment by rektdeckard** [comment]
2.0.0 is now live.
