### ISSUE TITLE
Non-Constant Invocations of IconData in v 2.0.0

### ISSUE THREAD

**Issue by JustinWeru12** [phosphor-icons/flutter#16]
I just upgraded to v 2.0.0 of the package and I get the following error when building the app. 
Flutter build cannot tree shake icons . 
Is it possible to add tree-shake support out of the box.
Here is part of the log.
`file:///...../Pub/Cache/hosted/pub.dev/phosphor_flutter-2.0.0/lib/src/phosphor_icons_light.dart:3746:19
file:///.....Pub/Cache/hosted/pub.dev/phosphor_flutter-2.0.0/lib/src/phosphor_icons_light.dart:3749:23
Target aot_android_asset_bundle failed: Exception: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.`

**Comment by rektdeckard** [comment]
I would defer to @rurickdev on that, but maybe you can declare icons in your view as `const`?

**Comment by CodeDoctorDE** [comment]
Maybe we can make these properties constant `final mapPin = PhosphorFlatIconData(0xebe0, 'Light');` if it works

**Comment by ajsharp** [comment]
Same here. If I try to build an ios app using, for example `PhosphorIcons.regular.spinner` I get a build error `This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:`.

But if I sub that in for the literal `PhosphorFlatIconData(0xed16, 'Regular')` it builds normally.
