### ISSUE TITLE
Implement an initial rotation

### ISSUE THREAD

**Issue by AntoninBleu122** [phosphor-icons/flutter#21]
Hello ! 
It would be great if we could set a rotation to the icon.
For example, I would like to use the triangle icon to point downward. Instead of requesting a new icon for each angle desired, it could be easier to just pass a double for degrees or radians to the PhosphorIcon class.

**Comment by k-ane** [comment]
I think to achieve what you want it would be simpler to wrap an icon widget with a transform. Here is an example widget that would allow you to set an angle in radians, flip horizontally and flip vertically

```
class IconX extends StatelessWidget {
  const IconX(
    this.icon, {
    this.flipHorizontal = false,
    this.flipVertical = false,
    this.angle,
    super.key,
  });

  final IconData icon;

  /// Flip icon from left to right
  final bool flipHorizontal;

  /// Flip icon from top to bottom
  final bool flipVertical;

  /// Rotate icon some amount
  final double? angle;

  @override
  Widget build(BuildContext context) {
    final scaledIcon = Transform.scale(
      scaleX: flipHorizontal ? -1 : 1,
      scaleY: flipVertical ? -1 : 1,
      child: Icon(icon),
    );

    if (angle == null) return scaledIcon;

    return Transform.rotate(
      angle: angle!,
      child: scaledIcon,
    );
  }
}
```

**Comment by rurickdev** [comment]
Agree with @k-ane 
It is not responsibility of the icon pack to transform itself, is better to let the parent widget do that.
