### ISSUE TITLE
Duotone icons  looks like  regular in master branch

### ISSUE THREAD

**Issue by heralight** [phosphor-icons/flutter#23]
Hello!
Thank you for your great icons,

After upgrade from 1.4 to master,  not 2.0.0 due to the const problem; I tested the PhosphorIconsDuotone implementation.
with the code :
Icon(PhosphorIconsDuotone.bookmarkSimple)

look exactly like 
Icon(PhosphorIconsRegular.bookmarkSimple)

best regards,

Alexandre

**Comment by luis901101** [comment]
AFAIK opacity is not allowed in font glyphs, so you need to use `PhosphorIcon` widget which adds the necessary Opacity when using a duotone icon.

**Comment by luis901101** [comment]
Just in case you want to use `PhosphorIcon` widget globally in your project maybe you want to check this [PR26](https://github.com/phosphor-icons/flutter/pull/26), which allows to use `PhosphorIcon` with generic IconData.

**Comment by rurickdev** [comment]
closing because the comment from @luis901101 is right. also the mentioned The PR #26 got merged
