### ISSUE TITLE
Error to build app phosphor_flutter-2.0.0

### ISSUE THREAD

**Issue by Ngochiendev** [phosphor-icons/flutter#28]
![Ảnh màn hình 2023-09-20 lúc 14 14 01](https://github.com/phosphor-icons/flutter/assets/111303461/35b15ed6-4d44-48a6-b4e1-92255137797f)

**Comment by Ngochiendev** [comment]
If I use --no-tree-shake-icons then I think it is not an effective solution. I want a radical solution

**Comment by Ngochiendev** [comment]
> I have the same issue. Do you fixed it @Ngochiendev ?

Temporary solution is to use  **--no-tree-shake-icons**

**Comment by rektdeckard** [comment]
An alternative is now available in `2.1.0` -- you can import each weight explicitly (e.g. `PhosphorIconsBold`) which will allow tree-shaking of the icons used from that font.
