### ISSUE TITLE
Future support

### ISSUE THREAD

**Issue by arscodicis** [phosphor-icons/flutter#34]
Its been over a year since this Flutter library for Phosphor Icons has been updated. 

Are there any plans to update this soon?

**Comment by rektdeckard** [comment]
It has just been updated. We have a typical update cadence of about 6-12 months for major releases, this is normal. There were no major bugs in the last year, so there were no updates while we were working on new icons.

**Comment by rektdeckard** [comment]
In this case, the flutter lib lagged behind the rest because though I own this repo, I am not a regular flutter user or the normal maintainer of the package.

**Comment by arscodicis** [comment]
Great, thanks for your support.
