### ISSUE TITLE
Export icons by type

### ISSUE THREAD

**Issue by narcodico** [phosphor-icons/flutter#9]
Hey @rektdeckard 👋

Great icon set! Would you mind also exporting lists or maps of icons grouped by type? e.g.: normal, bold, etc.

Thanks!

**Comment by rektdeckard** [comment]
Hu @narcodico, sorry I haven't got back to you. We're launching a 2.0 release very soon that has the weights split up by default!

**Comment by rektdeckard** [comment]
2.0.0 is live with icon weights and backing fonts split.

**Comment by narcodico** [comment]
@rektdeckard  would like to suggest a couple improvements to the current approach. You guys could go something around the likes of:

```
abstract class PhosphorIcons {
  static const bold = PhosphorIconsBold();
}
```
```
 class PhosphorIconsBold {
  const PhosphorIconsBold();
  
  final  addressBook = const PhosphorFlatIconData(0xe900, 'Bold');
  ...

  List<PhosphorFlatIconData> get icons => [addressBook, ...];
}
```

Exposing an `icons` getter with all the icons for that style would be extremely useful for dynamic features where all icons are needed, cause it's rather difficult for developers to keep track of which icons are being added, renamed, etc.
